config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  root to: "users#sign_up"

  resource :users, only: [:create, :edit, :update] do
    collection do
      get :sign_up
      get :sign_in
      post :login
      delete :sign_out
    end
  end

  resource :coupon
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  validates :email, presence: true, uniqueness: true

  # before_create :encrypt_password

  #* keyword argument
  # def self.login(account:, password:)
  # def login(options)
  #   if options[:account] and options[:password]  
  #     User.find_by(account: options[:account],
  #             password: bigbang(options[:password]))
  #             # password: Digest::SHA1.hexdigest("x#{options[:password]}y"))
  #   end
  # end
  
  # private
  # def encrypt_password
  #   # self.password = bigbang(self.password)
  #   #* 右方的 password 方法可拿掉 self
  #   self.password = bigbang(password)
  # end

  # def bigbang(string)
  #   string = "x#{string}y"
  #   Digest::SHA1.hexdigest(string)
  # end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private
  def current_user
    @current_user ||= User.find_by(id: session[:user_token]) # if user_signed_in?
  end
  
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController

  def show
    @user = current_user
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    redirect_to , notice: 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def sign_up
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      sign_in_user(@user)
      redirect_to coupon_path, notice: "會員註冊成功"
    else
      flash[:notice] = "請完成資料填寫"
      render :sign_up
    end
  end

  def sign_out
    sign_out_user
    redirect_to root_path, notice: "您已登出，掰掰掰掰"
  end


  def sign_in
    @user = User.new
    coupon_path
  end

  def login
    user = User.new.login(user_params)
    
    if user
      sign_in_user(user)
      redirect_to coupon_path, notice: "歡迎光臨"
    else
      redirect_to sign_in_users_path, notice: "帳號或密碼輸入錯誤"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :id_number, :phone_number, :password)
  end

  def sign_in_user(user)
    session[:user_token] = user.id
  end

  def sign_out_user
    session[:user_token] = nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/coupons/show.html.erb
<h1>Coupon show</h1>

<div data-controller="coupon">
  <%= form_for @user, url: coupon_path do |f| %>
    <div>
      <%= f.label :name, "姓名" %>
      <%= f.text_field :name, required: true %>
    </div>
  
    <div>
      <%= f.label :id_number, '身分證字號' %>
      <%= f.text_field :id_number, required: true %>
    </div>
  
    <div>
      <%= f.label :phone_number, '手機號碼' %>
      <%= f.text_field :phone_number, required: true %>
    </div>
  
    <div>
      <%= f.submit "兌換" %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<h1>ROOT</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/sign_in.html.erb
<h1>安安你好請登入</h1>

<%= form_for(@user, url: login_users_path) do |f| %>
  <div>
    <%= f.label :email, 'Email' %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password, "密碼" %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.submit "登入" %>
  </div>
<% end %>

app/views/users/sign_up.html.erb
<h1>安安你好請註冊新帳號</h1>
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@user) do |f| %>

  <div>
    <%= f.label :name, '姓名' %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :id_number, '身分證字號' %>
    <%= f.text_field :id_number %>
  </div>

  <div>
    <%= f.label :phone_number, '手機號碼' %>
    <%= f.text_field :phone_number %>
  </div>

  <div>
    <%= f.label :email, 'Email' %>
    <%= f.text_field :email %>
  </div>
  
  <div>
    <%= f.label :password, '密碼' %>
    <%= f.text_field :password %>
  </div>
  
  <div>
    <%= f.submit '送出' %>
  </div>

<% end %>

<div>
  <%= link_to '登入', sign_in_users_path %>
</div>